version: '3.8'

services:
  db_mysql:
    container_name: mysql_owl-writey
    image: mysql:8.0
    restart: always
    command: --max_allowed_packet=268435456
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./docker/mysql/setup:/docker-entrypoint-initdb.d
      - my-db:/var/lib/mysql
volumes:
  my-db:
